### ISSUE TITLE
Accessibility Hackathon Training Day ToDo List

### ISSUE THREAD

**Issue by jackiekazil** [18F/training#25]
This is a general running todo list... 
### General todos
- [x] Figure out who THE champion is to lead! (All)
- [x] Reach out to Digital Gov University for recording (Pia and Jackie)
- [x] Combine the list of folks (Alan)
- [x] Sign up for reach on the spreadsheet (Everyone)
- [x] Pre-event -- Training? -- Have a session to help folks figure out what is what with websites?
### Data brief (Rebecca)
- [x] Data 
- [x] Tools
- [x] 18F data.gov website
- [x] Problem statements
- [x] Example on project open data.
### By next week
- [x] Report out the convos we have had
- [x] Label who needs reach out in the list
- [x] Everyone bring by ideas on who we want to speak
- [x] Jackie & Nick figures out web

**Comment by jackiekazil** [comment]
Pre-event -- Training? --- This was put on hold for a future training session so it isn't rushed.
