### ISSUE TITLE
Accessibility Hackathon Training Day ToDo List Due 02/26/15

### ISSUE THREAD

**Issue by jackiekazil** [18F/training#26]
Here is our Todo list for this week:
- [x] Reorg & email copy of the spreadsheet
- [x] continue working on accessibility resource site
- [x] comms plan
- [x] identifying all the content pieces we need for specific asks next week (Jackie)
